name: CI Build Flatpak

on:
  push:
    branches: [main]
  pull_request: {}
  workflow_dispatch:

jobs:
  flatpak:
    name: Flatpak x86_64
    runs-on: tumbleweed
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v6

      - name: Build repository
        run: |
          flatpak-builder --force-clean \
            --install-deps-from=flathub \
            --repo=repo \
            builddir \
            com.t3tools.t3code.yml

      - name: Build bundle
        run: |
          flatpak build-bundle \
            repo \
            t3code.flatpak \
            com.t3tools.t3code \
            --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo

      - name: Create checksum
        run: sha256sum t3code.flatpak > t3code.flatpak.sha256

      - name: Upload Flatpak and checksum
        uses: https://data.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: t3code-flatpak
          path: |
            t3code.flatpak
            t3code.flatpak.sha256
          if-no-files-found: error
          compression-level: 0
